# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ed6864a85f875b133b333e46c28567a9ac3ad0da70b0dc9119175c6a94357e0370db227b5a0ca40da713507c3c558b3bb79a4d056e2e8854ce3c33b6fb6258a

test:
  secret_key_base: 5769a546297e6e3624d5b3c83f5419034252dd75d67159f29c0597f1a30a3506568d1162c304e50cdde5f79fe0cbc94204ba1686ca91c3446b201a0662ec6be2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
